#!python
APP_ID = ""
APP_NAME = "blah_tool"
APP_SECRET = ""
TENANT= "kazoo.onmicrosoft.com"
INTUNEWIN_DIR = "path/to/intunewin" # directory that contains .intunewin, .intunewin.json, and .portal.intunewin


ADDITIONAL_APP_PROPERTIES = {
    "description": "written by blahblah",
    "installCommandLine": "some.exe --blah",
    "uninstallCommandLine": "rm -rf C:\\Program \\Files\\some.exe",
    # list of rules
    # rules can be anything that implements win32LobAppRule such as these:
    # win32lobappfilesystemrule: https://docs.microsoft.com/en-us/graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0
    # win32lobappregistryrule: https://docs.microsoft.com/en-us/graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0
    "rules": [{
        "@odata.type": "#microsoft.graph.win32LobAppFileSystemRule",
        "ruleType": "detection",
        "path": "C:\\Path\\To\\Some\\Directory\\ThatOnlyExistsAfterInstall",
        "fileOrFolderName": "relative\\path\\ToSomeFileThatExistsInAboveDirectoryAfterInstall",
        "check32BitOn64System": False,
        "operationType": "exists",
        "operator": "notConfigured"
    }]
}